### ISSUE TITLE
Express PNG Headers

### ISSUE THREAD

**Issue by clarkhacks** [clarkhacks/WebLense#6]
```bash
Error: Can't set headers after they are sent.
8:57 AM
    at SendStream.headersAlreadySent (/app/node_modules/send/index.js:390:13)
8:57 AM
    at SendStream.send (/app/node_modules/send/index.js:618:10)
8:57 AM
    at onstat (/app/node_modules/send/index.js:730:10)
8:57 AM
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by clarkhacks** [comment]
Fixed
